### ISSUE TITLE
looping of encode function

### ISSUE THREAD

**Issue by zirotu02** [Helium-He/Image-Steganography#1]
![Screenshot (1)](https://user-images.githubusercontent.com/34594619/86882921-ad55b680-c10e-11ea-99f4-658b58adae52.png)

i can help with this situation, if you want checkout my version of your code (https://github.com/malay21/image-steganography.git)

**Comment by Helium-He** [comment]
No problem.Bring the solution on

**Comment by zirotu02** [comment]
def e_path(self,ef):  

     
        **ep= Frame(root)**


        myfile = tkinter.filedialog.askopenfilename(filetypes = ([('png', '*.png'),('jpeg', '*.jpeg'),('jpg', '*.jpg'),('All Files', '*.*')]))
        #myfile = tkinter.filedialog.askopenfilename()
        if not myfile:
            messagebox.showerror("error","you have selected nothing !")
        else:
            myimg = Image.open(myfile)
            myimage = myimg.resize((250,150))


            **ef.destroy()**


            img = ImageTk.PhotoImage(myimage)
            l3= Label(ep,text='selected image')
            l3.grid()
            panel = Label(ep, image=img)
            panel.image = img
            self.o_image_size = os.stat(myfile)
            self.o_image_w, self.o_image_h = myimg.size
            panel.grid()
            l2 = Label(ep, text='Enter the message')
            l2.config(font=('courier',18))
            l2.grid(pady=15)
            text_area = Text(ep, width=50, height=10)
            text_area.grid()
            encode_button = Button(ep, text='cancel', command=lambda : frames.home(self,ep))
            encode_button.config(font=('courier',16))
            back_button = Button(ep, text='Encode', command=lambda : [func.e_fun(self,text_area,myimg),frames.home(self,ep)])
            back_button.config(font=('courier',16))
            back_button.grid(pady=15)
            encode_button.grid()
            ep.grid(row=1)


just destroy that old frame and create new just like this it will solve the isue
![Screenshot from 2020-07-10 21-13-42](https://user-images.githubusercontent.com/34594619/87172741-57416880-c2f2-11ea-83b2-2964a0c5a338.png)

**Comment by Helium-He** [comment]
Ok

**Comment by zirotu02** [comment]
also add 

" text_area.configure(state='disabled')  "
to make text box non editable for user.

and 

temp=os.path.splitext(os.path.basename(myimg.filename))[0] 
newimg.save(tkinter.filedialog.asksaveasfilename(initialfile=temp,filetypes = ([('png', '*.png')]),defaultextension=".png"))

to give an option to save with same filename
